version: '3.7'

services:
  virtualenv:
    image: atsigncompany/virtualenv:vip
    ports:
      - '127.0.0.1:6379:6379'
      - '64:64'
      - '127.0.0.1:9001:9001'
      - '25000-25019:25000-25019'
    extra_hosts:
      - 'vip.ve.atsign.zone:127.0.0.1'
